In [57]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import os
from os.path import join

In [58]:
def str_to_path(path_str):
    '''Converts windows path string to os.path'''
    path_list = path_str.split('\\')
    path = os.path.join(path_list[0], os.sep, *path_list[1:])
    return path

In [59]:
path = str_to_path(r"N:\WATER_Program\Groundwater\Global_GDE_Map\data")
plots_in = os.path.join(path, "sPlotOpen", "sPlotOpen_header(2).txt")
veg_in = os.path.join(path, "sPlotOpen", "sPlotOpen_DT(1).txt")
tbl_in = str_to_path(r"N:\WATER_Program\Groundwater\Global_GDE_Map\tables\sPlotOpen_GDE_review_20230407.csv")
tbl_in2 = str_to_path(r"N:\WATER_Program\Groundwater\Global_GDE_Map\tables\sPlotOpen_GDE_review_20230407_forToderichReview_Kristina Last_KK.xlsx")
tbl_out = str_to_path(r"N:\WATER_Program\Groundwater\Global_GDE_Map\tables\sPlotOpen_GDE_points_20230418.csv")
tbl_out2 = str_to_path(r"N:\WATER_Program\Groundwater\Global_GDE_Map\tables\sPlotOpen_GDE_review_20230418.csv")

In [60]:
# Read in extract from Google Sheets
df = pd.read_csv(tbl_in)
df = df.rename(columns={'GDE_Class(2=not groundwater-dependent;1= groundwater-dependent)': 'GDE_Class', 'GDE_Certainty_(1=High;2=Medium;3=Low)': 'GDE_Cert'})
df

,Species,Continent,Count_plots,GDE_Class,GDE_Cert,References,ExpertName,ExpertEmail,Notes,Species_Kristina_values,Species_sPlot_values,Species_Kristina,Species_sPlot
0,/new species,Asia,1,1.0,2.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,NaN,NaN,NaN,NaN,NaN
1,Abarema adenophora,Asia,2,1.0,1.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,"restricted to desert areas in central Asia, Af...",Abarema adenophora/rare species,Abarema adenophora,NaN,NaN
2,Abelia corymbosa,Asia,2,1.0,1.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,Native to Central Asia,NaN,NaN,NaN,NaN
3,Abelia mosanensis,Asia,1,1.0,2.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,evergreen shrubs are native to eastern Asia (J...,NaN,NaN,NaN,NaN
4,Abies alba,Europe,2113,1.0,2.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56045,Zygophyllum teretifolium,Africa,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56046,Zygophyllum xanthoxylum,Asia,68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56047,Zygostigma australe,South America,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56048,NaN,Africa,632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56049,NaN,South America,105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
# Read in edits from Kristina
df1 = pd.read_excel(tbl_in2, skiprows=1)
df1 = df1.rename(columns={'GDE_Class(2=not groundwater-dependent;1= groundwater-dependent)': 'GDE_Class', 'GDE_Certainty_(1=High;2=Medium;3=Low)': 'GDE_Cert'})
df1

,Species,Continent,Count_plots,GDE_Class,GDE_Cert,References,ExpertName,ExpertEmail,Notes
0,Oryza sativa,Asia,57,2,2,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,only for the perennial wild form of rice
1,Acalypha australis,Asia,64,2,3,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,Asia/rare in central Pamir Alai mountains (Taj...
2,Acalypha indica,Asia,26,2,3,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,Asia
3,Acanthephippium striatum,Asia,5,2,3,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,Asia/ doesn't occur in Asian countries
4,Acanthephippium sylhetense,Asia,1,2,3,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,"Asia/southestern Asia, Taiwan, China, Japan"
...,...,...,...,...,...,...,...,...,...
1711,Robinia pseudoacacia,Asia,4,1,1,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,"Asia/Caucasus, Crimea and Central Asia"
1712,Arctagrostis latifolia,Europe,12,1,1,NaN,NaN,NaN,NaN
1713,Acacia petraea,Oceania,1,1,1,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,NaN
1714,Ampelopsis glandulosa,North America,1,1,1,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,"Porcelain-berry is a deciduous, woody perennia..."
1715,Abrus precatorius,Asia,1,1,1,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,Asia/subtropical Asia and Africa .Woody perenn...

In [62]:
#Error Checks on review table
print(df.GDE_Class.unique().tolist())
print(df.GDE_Cert.unique().tolist())
dfa = (df.groupby(['GDE_Class', 'GDE_Cert'], dropna=False)
           .agg({'Species':'count', 'Count_plots':'sum'})
           .reset_index()
           .rename(columns={'Species':'Count_species'})
          )
print(dfa)
# Get only the species with GDE class data
dfb = df.dropna(subset=['GDE_Class'])
print(len(df))

print(dfb.Continent.unique().tolist())
print(dfb[dfb.duplicated(['Species','Continent'], keep=False)].sort_values(by=['Species'], ascending=[True]))
#Remove any duplicate rows based on a subset of rows
dfb = dfb.drop_duplicates(subset=['Species','Continent'], keep='first')
print(len(dfb))

[1.0, 2.0, nan]
[2.0, 1.0, 3.0, nan]
   GDE_Class  GDE_Cert  Count_species  Count_plots
0        1.0       1.0            861        32391
1        1.0       2.0            601        21570
2        1.0       3.0            276         6237
3        2.0       1.0              3          323
4        2.0       2.0             53         1262
5        2.0       3.0             13          266
6        NaN       2.0              1          187
7        NaN       NaN          54240      1883128
56050
['Asia', 'Europe', 'Oceania', 'Africa', 'North America', 'South America']
               Species Continent  Count_plots  GDE_Class  GDE_Cert References  \
552  Breonia chinensis      Asia           11        1.0       2.0        NaN
553  Breonia chinensis      Asia            2        1.0       1.0        NaN

             ExpertName                ExpertEmail                  Notes  \
552  Kristina Toderich   ktoderich@tottori-u.ac.jp  Asia/mostly to China
553  Kristina Toderich   ktoderich@tottori-u.ac.jp                    NaN

            Species_Kristina_values Species_sPlot_values Species_Kristina  \
552  Breonia chinensis/endemic tree    Breonia chinensis              NaN
553          Breonia chinensis/tree    Breonia chinensis              NaN

    Species_sPlot
552           NaN
553           NaN
1806

In [63]:
#Error Checks on new table
print(df1.GDE_Class.unique().tolist())
print(df1.GDE_Cert.unique().tolist())
df1a = (df1.groupby(['GDE_Class', 'GDE_Cert'], dropna=False)
           .agg({'Species':'count', 'Count_plots':'sum'})
           .reset_index()
           .rename(columns={'Species':'Count_species'})
          )
print(df1a)
# Get only the species with GDE class data
df1b = df1.dropna(subset=['GDE_Class'])
print(len(df1))
print(len(df1b))

print(df1b.Continent.unique().tolist())
print(df1b[df1b.duplicated(['Species','Continent'], keep=False)].sort_values(by=['Species'], ascending=[True]))
#Remove any duplicate rows based on a subset of rows
df1b = df1b.drop_duplicates(subset=['Species','Continent'], keep='first')
print(len(df1b))

[2, 1]
[2, 3, 1]
   GDE_Class  GDE_Cert  Count_species  Count_plots
0          1         1            812        24837
1          1         2            565        20054
2          1         3            273         6042
3          2         2             53         1262
4          2         3             13          266
1716
1716
['Asia', 'Europe', 'Oceania', 'North America', 'South America']
               Species Continent  Count_plots  GDE_Class  GDE_Cert References  \
570  Breonia chinensis      Asia           11          1         2        NaN
571  Breonia chinensis      Asia            2          1         1        NaN

             ExpertName                ExpertEmail                  Notes
570  Kristina Toderich   ktoderich@tottori-u.ac.jp  Asia/mostly to China
571  Kristina Toderich   ktoderich@tottori-u.ac.jp                    NaN
1715

In [64]:
# Flag rows that are missing or to fix on review table
df1c = pd.merge(df1b, dfb, how='left', on=['Species', 'Continent', 'Count_plots'])
df1c[df1c['GDE_Class_y'].isna()]

,Species,Continent,Count_plots,GDE_Class_x,GDE_Cert_x,References_x,ExpertName_x,ExpertEmail_x,Notes_x,GDE_Class_y,GDE_Cert_y,References_y,ExpertName_y,ExpertEmail_y,Notes_y,Species_Kristina_values,Species_sPlot_values,Species_Kristina,Species_sPlot
556,Bolboschoenus,Asia,4,1,2,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,"(KK): Changed ""Bolboschoenus/salt marsh specie...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1712,Acacia petraea,Oceania,1,1,1,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1713,Ampelopsis glandulosa,North America,1,1,1,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,"Porcelain-berry is a deciduous, woody perennia...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1714,Abrus precatorius,Asia,1,1,1,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,Asia/subtropical Asia and Africa .Woody perenn...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
# Fix any reviewer name records with a space at the end
df1b['ExpertName'] = df1b['ExpertName'].replace('Kristina Toderich ', 'Kristina Toderich')
dfb['ExpertName'] = dfb['ExpertName'].replace('Kristina Toderich ', 'Kristina Toderich')

In [66]:
dfb.ExpertName.unique().tolist()

['Kristina Toderich', 'Zach Freed', nan, 'Kirk Klausmeyer', 'Nancy Job']

In [67]:
print(len(dfb.loc[dfb.ExpertName == 'Kristina Toderich']))
print(len(df1b.loc[df1b.ExpertName == 'Kristina Toderich']))

1710
1714

In [68]:
# Replace Kristina's columns with the newer dataset
dfc = dfb.loc[dfb.ExpertName != 'Kristina Toderich']
dfd = pd.concat([dfc, df1b], ignore_index=True)
dfd = dfd.drop(['Species_Kristina_values', 'Species_sPlot_values', 'Species_Kristina', 'Species_sPlot'], axis=1)
dfd

,Species,Continent,Count_plots,GDE_Class,GDE_Cert,References,ExpertName,ExpertEmail,Notes
0,Acacia acanthoclada,Oceania,1,1.0,2.0,"Lamontagne, S., Cook, P.G., O'Grady, A. & Eamu...",Zach Freed,zach.freed@tnc.org,NaN
1,Acacia acradenia,Oceania,8,1.0,2.0,"Lamontagne, S., Cook, P.G., O'Grady, A. & Eamu...",Zach Freed,zach.freed@tnc.org,NaN
2,Acacia acuminata,Oceania,1,1.0,2.0,"Lamontagne, S., Cook, P.G., O'Grady, A. & Eamu...",Zach Freed,zach.freed@tnc.org,NaN
3,Acacia adoxa,Oceania,2,1.0,2.0,"Lamontagne, S., Cook, P.G., O'Grady, A. & Eamu...",Zach Freed,zach.freed@tnc.org,NaN
4,Acacia adsurgens,Oceania,19,1.0,2.0,"Lamontagne, S., Cook, P.G., O'Grady, A. & Eamu...",Zach Freed,zach.freed@tnc.org,NaN
...,...,...,...,...,...,...,...,...,...
1806,Robinia pseudoacacia,Asia,4,1.0,1.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,"Asia/Caucasus, Crimea and Central Asia"
1807,Arctagrostis latifolia,Europe,12,1.0,1.0,NaN,NaN,NaN,NaN
1808,Acacia petraea,Oceania,1,1.0,1.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,NaN
1809,Ampelopsis glandulosa,North America,1,1.0,1.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,"Porcelain-berry is a deciduous, woody perennia..."
1810,Abrus precatorius,Asia,1,1.0,1.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,Asia/subtropical Asia and Africa .Woody perenn...

In [69]:
# Review duplicates
dfd[dfd.duplicated(subset=['Species', 'Continent'], keep=False)]

,Species,Continent,Count_plots,GDE_Class,GDE_Cert,References,ExpertName,ExpertEmail,Notes
22,Acacia hamulosa,Asia,7,1.0,1.0,NaN,NaN,NaN,NaN
26,Arctagrostis latifolia,Europe,12,1.0,1.0,NaN,NaN,NaN,NaN
181,Acacia hamulosa,Asia,7,1.0,1.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,NaN
1807,Arctagrostis latifolia,Europe,12,1.0,1.0,NaN,NaN,NaN,NaN

In [70]:
# Drop duplicates
dfd = dfd.sort_values(by=['ExpertName'], ascending=[True])
dfd = dfd.drop_duplicates(subset=['Species', 'Continent'], keep='first')
dfd

,Species,Continent,Count_plots,GDE_Class,GDE_Cert,References,ExpertName,ExpertEmail,Notes
64,Grewia flava,Africa,109,1.0,1.0,"Weiersbye, I.M. and Witkowski, E.T.F., 2007. I...",Kirk Klausmeyer,kklausmeyer@tnc.org,NaN
70,Mundulea sericea,Africa,31,1.0,1.0,"Weiersbye, I.M. and Witkowski, E.T.F., 2007. I...",Kirk Klausmeyer,kklausmeyer@tnc.org,NaN
71,Phragmites australis,Europe,1353,1.0,1.0,"El-Hokayem, LÃ©onard, Pantaleone De Vita, and C...",Kirk Klausmeyer,kklausmeyer@tnc.org,NaN
58,Elephantorrhiza elephantina,Africa,7,1.0,1.0,"Weiersbye, I.M. and Witkowski, E.T.F., 2007. I...",Kirk Klausmeyer,kklausmeyer@tnc.org,NaN
74,Populus nigra,Europe,173,1.0,1.0,"El-Hokayem, LÃ©onard, Pantaleone De Vita, and C...",Kirk Klausmeyer,kklausmeyer@tnc.org,NaN
...,...,...,...,...,...,...,...,...,...
59,Eucalyptus camaldulensis,Oceania,444,1.0,1.0,"Dawson, T.E. & Pate, J.S. Seasonal water uptak...",Zach Freed,zach.freed@tnc.org,NaN
60,Eucalyptus camaldulensis,Asia,12,1.0,1.0,"Dawson, T.E. & Pate, J.S. Seasonal water uptak...",Zach Freed,zach.freed@tnc.org,NaN
51,Celtis,Africa,1,1.0,2.0,"Hultine, K.R., Williams, D.G., Burgess, S.S.O....",Zach Freed,zach.freed@tnc.org,NaN
0,Acacia acanthoclada,Oceania,1,1.0,2.0,"Lamontagne, S., Cook, P.G., O'Grady, A. & Eamu...",Zach Freed,zach.freed@tnc.org,NaN
26,Arctagrostis latifolia,Europe,12,1.0,1.0,NaN,NaN,NaN,NaN

In [71]:
# Read in plot data
df1 = pd.read_csv(plots_in, sep='\t')
df1

E:\Users\kklausmeyer\AppData\Local\Temp\21\ipykernel_44584\168297315.py:2: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(plots_in, sep='\t')

,PlotObservationID,GIVD_ID,Dataset,Continent,Country,Biome,Date_of_recording,Latitude,Longitude,Location_uncertainty,Releve_area,Plant_recorded,Elevation,Aspect,Slope,is_forest,ESY,Naturalness,Forest,Shrubland,Grassland,Wetland,Sparse_vegetation,Cover_total,Cover_tree_layer,Cover_shrub_layer,Cover_herb_layer,Cover_moss_layer,Cover_lichen_layer,Cover_algae_layer,Cover_litter_layer,Cover_bare_rocks,Cover_cryptogams,Cover_bare_soil,Height_trees_highest,Height_trees_lowest,Height_shrubs_highest,Height_shrubs_lowest,Height_herbs_average,Height_herbs_lowest,Height_herbs_highest,SoilClim_PC1,SoilClim_PC2,Resample_1,Resample_2,Resample_3,Resample_1_consensus
0,16,NA-US-014,Aava,North America,United States,Boreal zone,1980-01-01,62.420000,-154.180000,1000.0,NaN,Not specified,1790.0,NaN,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,30.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.660,0.546,True,False,False,True
1,17,NA-US-014,Aava,North America,United States,Boreal zone,1980-01-01,62.420000,-154.180000,1000.0,NaN,Not specified,1750.0,NaN,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,5.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.660,0.546,True,False,False,True
2,18,NA-US-014,Aava,North America,United States,Boreal zone,1980-01-01,62.420000,-154.180000,1000.0,NaN,Not specified,1750.0,NaN,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,5.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.660,0.546,False,False,True,False
3,20,NA-US-014,Aava,North America,United States,Boreal zone,1980-01-01,62.420000,-154.180000,1000.0,NaN,Not specified,1520.0,NaN,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,60.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.660,0.546,False,True,False,False
4,22,NA-US-014,Aava,North America,United States,Boreal zone,1980-01-01,62.420000,-154.180000,1000.0,NaN,Not specified,1550.0,NaN,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,65.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.660,0.546,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95099,1126749,EU-00-020,European wetlands,Europe,Latvia,Temperate midlatitudes,2010-08-19,56.287870,27.273862,10.0,4.0,Not specified,NaN,NaN,NaN,NaN,?,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,10.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.599,0.775,True,False,False,True
95100,1126761,EU-00-020,European wetlands,Europe,Latvia,Temperate midlatitudes,2009-06-19,56.939965,23.598014,10.0,4.0,Not specified,NaN,NaN,NaN,False,Y-Gra,Semi-natural,False,False,True,False,False,93.0,NaN,NaN,90.0,3.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.416,0.690,False,False,True,False
95101,1126769,EU-00-020,European wetlands,Europe,Latvia,Temperate midlatitudes,2009-06-19,56.939965,23.598014,10.0,4.0,Not specified,NaN,NaN,NaN,False,Y-Gra,Semi-natural,False,False,True,False,False,93.0,NaN,4.0,91.0,5.0,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.416,0.690,False,True,False,False
95102,1126774,EU-00-020,European wetlands,Europe,Latvia,Temperate midlatitudes,2003-09-06,57.248222,22.147667,10.0,4.0,Not specified,NaN,NaN,NaN,NaN,?,NaN,NaN,NaN,NaN,NaN,NaN,100.0,NaN,NaN,38.0,89.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.065,0.849,False,False,True,False
95103,1126790,EU-00-020,European wetlands,Europe,Latvia,Temperate midlatitudes,2003-07-19,57.563967,26.892074,10.0,4.0,Not specified,NaN,NaN,NaN,False,D32,Natural,False,True,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.738,1.164,False,False,True,False

In [72]:
# Read in species data
df2 = pd.read_csv(veg_in, sep='\t')
df2

,PlotObservationID,Species,Original_species,Original_abundance,Abundance_scale,Relative_cover
0,16,Festuca brachyphylla,Festuca brachyphylla,10.0,CoverPerc,0.277778
1,16,Potentilla elegans,Potentilla elegans,25.0,CoverPerc,0.694444
2,16,Saxifraga serpyllifolia,Saxifraga serpyllifolia,1.0,CoverPerc,0.027778
3,17,Festuca brachyphylla,Festuca brachyphylla,1.0,CoverPerc,0.038462
4,17,Potentilla elegans,Potentilla elegans,25.0,CoverPerc,0.961538
...,...,...,...,...,...,...
1945379,1126790,Potentilla erecta,Potentilla erecta,0.3,CoverPerc,0.006276
1945380,1126790,Salix lapponum,Salix lapponum,1.0,CoverPerc,0.020921
1945381,1126790,Stellaria palustris,Stellaria palustris,0.5,CoverPerc,0.010460
1945382,1126790,Trichophorum alpinum,Scirpus hudsonianus,18.0,CoverPerc,0.376569
1945383,1126790,Vaccinium oxycoccos,Vaccinium oxycoccos,8.0,CoverPerc,0.167364

In [73]:
# Check species data from review table to ensure all have a match in the veg data
df3 = df2[['Species']].drop_duplicates()

# Reset the index of the new DataFrame
df3.reset_index(drop=True, inplace=True)
df3['sPlot'] = 1

df4 = pd.merge(dfd, df3, on='Species', how='left')
df5 = df4[df4['sPlot'].isna()]
df5

,Species,Continent,Count_plots,GDE_Class,GDE_Cert,References,ExpertName,ExpertEmail,Notes,sPlot
1122,/new species,Asia,1,1.0,2.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,NaN,NaN

In [74]:
# Check the original data to see if those records exist
df3['Species'] = df3['Species'].fillna('')
df3[df3['Species'].str.startswith('Abrus precatorius')].sort_values(by='Species')

                Species  sPlot
7629  Abrus precatorius      1

In [75]:
# Join the plot data to the sPlot species table
df6 = pd.merge(df2, df1, on='PlotObservationID', how='left')
df6

,PlotObservationID,Species,Original_species,Original_abundance,Abundance_scale,Relative_cover,GIVD_ID,Dataset,Continent,Country,Biome,Date_of_recording,Latitude,Longitude,Location_uncertainty,Releve_area,Plant_recorded,Elevation,Aspect,Slope,is_forest,ESY,Naturalness,Forest,Shrubland,Grassland,Wetland,Sparse_vegetation,Cover_total,Cover_tree_layer,Cover_shrub_layer,Cover_herb_layer,Cover_moss_layer,Cover_lichen_layer,Cover_algae_layer,Cover_litter_layer,Cover_bare_rocks,Cover_cryptogams,Cover_bare_soil,Height_trees_highest,Height_trees_lowest,Height_shrubs_highest,Height_shrubs_lowest,Height_herbs_average,Height_herbs_lowest,Height_herbs_highest,SoilClim_PC1,SoilClim_PC2,Resample_1,Resample_2,Resample_3,Resample_1_consensus
0,16,Festuca brachyphylla,Festuca brachyphylla,10.0,CoverPerc,0.277778,NA-US-014,Aava,North America,United States,Boreal zone,1980-01-01,62.420000,-154.180000,1000.0,NaN,Not specified,1790.0,NaN,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,30.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.660,0.546,True,False,False,True
1,16,Potentilla elegans,Potentilla elegans,25.0,CoverPerc,0.694444,NA-US-014,Aava,North America,United States,Boreal zone,1980-01-01,62.420000,-154.180000,1000.0,NaN,Not specified,1790.0,NaN,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,30.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.660,0.546,True,False,False,True
2,16,Saxifraga serpyllifolia,Saxifraga serpyllifolia,1.0,CoverPerc,0.027778,NA-US-014,Aava,North America,United States,Boreal zone,1980-01-01,62.420000,-154.180000,1000.0,NaN,Not specified,1790.0,NaN,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,30.0,NaN,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.660,0.546,True,False,False,True
3,17,Festuca brachyphylla,Festuca brachyphylla,1.0,CoverPerc,0.038462,NA-US-014,Aava,North America,United States,Boreal zone,1980-01-01,62.420000,-154.180000,1000.0,NaN,Not specified,1750.0,NaN,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,5.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.660,0.546,True,False,False,True
4,17,Potentilla elegans,Potentilla elegans,25.0,CoverPerc,0.961538,NA-US-014,Aava,North America,United States,Boreal zone,1980-01-01,62.420000,-154.180000,1000.0,NaN,Not specified,1750.0,NaN,0.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,5.0,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-3.660,0.546,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1945379,1126790,Potentilla erecta,Potentilla erecta,0.3,CoverPerc,0.006276,EU-00-020,European wetlands,Europe,Latvia,Temperate midlatitudes,2003-07-19,57.563967,26.892074,10.0,4.0,Not specified,NaN,NaN,NaN,False,D32,Natural,False,True,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.738,1.164,False,False,True,False
1945380,1126790,Salix lapponum,Salix lapponum,1.0,CoverPerc,0.020921,EU-00-020,European wetlands,Europe,Latvia,Temperate midlatitudes,2003-07-19,57.563967,26.892074,10.0,4.0,Not specified,NaN,NaN,NaN,False,D32,Natural,False,True,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.738,1.164,False,False,True,False
1945381,1126790,Stellaria palustris,Stellaria palustris,0.5,CoverPerc,0.010460,EU-00-020,European wetlands,Europe,Latvia,Temperate midlatitudes,2003-07-19,57.563967,26.892074,10.0,4.0,Not specified,NaN,NaN,NaN,False,D32,Natural,False,True,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.738,1.164,False,False,True,False
1945382,1126790,Trichophorum alpinum,Scirpus hudsonianus,18.0,CoverPerc,0.376569,EU-00-020,European wetlands,Europe,Latvia,Temperate midlatitudes,2003-07-19,57.563967,26.892074,10.0,4.0,Not specified,NaN,NaN,NaN,False,D32,Natural,False,True,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.738,1.164,False,False,True,False
1945383,1126790,Vaccinium oxycoccos,Vaccinium oxycoccos,8.0,CoverPerc,0.167364,EU-00-020,European wetlands,Europe,Latvia,Temperate midlatitudes,2003-07-19,57.563967,26.892074,10.0,4.0,Not specified,NaN,NaN,NaN,False,D32,Natural,False,True,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.738,1.164,False,False,True,False

In [76]:
# Join the GDE review data to the sPlot data
df7 = pd.merge(dfd, df6, on=['Species', 'Continent'], how='inner')
df7 = df7.rename(columns={'Latitude': 'latitude', 'Longitude': 'longitude'})
df7

,Species,Continent,Count_plots,GDE_Class,GDE_Cert,References,ExpertName,ExpertEmail,Notes,PlotObservationID,Original_species,Original_abundance,Abundance_scale,Relative_cover,GIVD_ID,Dataset,Country,Biome,Date_of_recording,latitude,longitude,Location_uncertainty,Releve_area,Plant_recorded,Elevation,Aspect,Slope,is_forest,ESY,Naturalness,Forest,Shrubland,Grassland,Wetland,Sparse_vegetation,Cover_total,Cover_tree_layer,Cover_shrub_layer,Cover_herb_layer,Cover_moss_layer,Cover_lichen_layer,Cover_algae_layer,Cover_litter_layer,Cover_bare_rocks,Cover_cryptogams,Cover_bare_soil,Height_trees_highest,Height_trees_lowest,Height_shrubs_highest,Height_shrubs_lowest,Height_herbs_average,Height_herbs_lowest,Height_herbs_highest,SoilClim_PC1,SoilClim_PC2,Resample_1,Resample_2,Resample_3,Resample_1_consensus
0,Grewia flava,Africa,109,1.0,1.0,"Weiersbye, I.M. and Witkowski, E.T.F., 2007. I...",Kirk Klausmeyer,kklausmeyer@tnc.org,NaN,1877,Grewia flava,7.0,CoverPerc,0.069569,AF-00-009,Angola,Botswana,Dry tropics and subtropics,2014-11-23,-18.815133,22.443617,4.0,100.0,Not specified,982.0,NaN,NaN,True,NaN,Semi-natural,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.574,-2.947,True,True,True,True
1,Grewia flava,Africa,109,1.0,1.0,"Weiersbye, I.M. and Witkowski, E.T.F., 2007. I...",Kirk Klausmeyer,kklausmeyer@tnc.org,NaN,1878,Grewia flava,3.0,CoverPerc,0.029050,AF-00-009,Angola,Botswana,Dry tropics and subtropics,2014-11-23,-18.815133,22.443617,4.0,1000.0,Not specified,982.0,NaN,NaN,True,NaN,Semi-natural,True,False,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.574,-2.947,True,True,True,True
2,Grewia flava,Africa,109,1.0,1.0,"Weiersbye, I.M. and Witkowski, E.T.F., 2007. I...",Kirk Klausmeyer,kklausmeyer@tnc.org,NaN,1892,Grewia flava,3.0,CoverPerc,0.032213,AF-00-009,Angola,Botswana,Dry tropics and subtropics,2014-11-20,-18.770867,22.404883,4.0,1000.0,Not specified,979.0,NaN,NaN,False,NaN,Semi-natural,False,True,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.579,-2.923,True,True,False,True
3,Grewia flava,Africa,109,1.0,1.0,"Weiersbye, I.M. and Witkowski, E.T.F., 2007. I...",Kirk Klausmeyer,kklausmeyer@tnc.org,NaN,25105,Grewia flava,1.0,CoverPerc,0.006305,AF-00-003,BIOTA_South_Africa,Namibia,Dry tropics and subtropics,2008-03-12,-18.305000,19.263889,1.0,1000.0,Not specified,0.0,360.0,0.0,False,NaN,NaN,False,True,False,False,False,100.0,2.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.439,-2.822,False,True,True,False
4,Grewia flava,Africa,109,1.0,1.0,"Weiersbye, I.M. and Witkowski, E.T.F., 2007. I...",Kirk Klausmeyer,kklausmeyer@tnc.org,NaN,25106,Grewia flava,5.0,CoverPerc,0.035286,AF-00-003,BIOTA_South_Africa,Namibia,Dry tropics and subtropics,2008-03-13,-18.305833,19.261667,1.0,1000.0,Not specified,0.0,360.0,0.0,False,NaN,NaN,False,True,False,False,False,100.0,5.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.439,-2.822,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62011,Arctagrostis latifolia,Europe,12,1.0,1.0,NaN,NaN,NaN,NaN,471526,Arctagrostis latifolia,1.0,CoverPerc,0.058824,EU-00-022,European Mire VDB,Russian Federation,Polar and subpolar zone,1929-01-01,69.705556,31.779444,10.0,25.0,Not specified,NaN,NaN,NaN,False,D32,Natural,False,True,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.758,1.963,False,False,True,True
62012,Arctagrostis latifolia,Europe,12,1.0,1.0,NaN,NaN,NaN,NaN,471527,Arctagrostis latifolia,1.0,CoverPerc,0.055556,EU-00-022,European Mire VDB,Russian Federation,Polar and subpolar zone,1929-01-01,69.705556,31.779444,10.0,25.0,Not specified,NaN,NaN,NaN,False,?,Natural,False,False,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.758,1.963,True,False,False,True
62013,Arctagrostis latifolia,Europe,12,1.0,1.0,NaN,NaN,NaN,NaN,471546,Arctagrostis latifolia,1.0,CoverPerc,0.066667,EU-00-022,European Mire VDB,Russian Federation,Polar and subpolar zone,1929-08-20,69.783333,31.900000,10.0,25.0,Not specified,NaN,NaN,NaN,False,?,Semi-natural,False,False,True,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.813,1.908,False,False,True,False
62014,Arctagrostis latifolia,Europe,12,1.0,1.0,NaN,NaN,NaN,NaN,471556,Arctagrostis latifolia,1.0,CoverPerc,0.166667,EU-00-022,European Mire VDB,Russian Federation,Polar and subpolar zone,1929-01-01,69.783333,31.900000,10.0,25.0,Not specified,NaN,NaN,NaN,False,?,Semi-natural,False,False,True,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.813,1.908,False,False,True,False
62015,Arctagrostis latifolia,Europe,12,1.0,1.0,NaN,NaN,NaN,NaN,471596,Arctagrostis latifolia,1.0,CoverPerc,0.037037,EU-00-022,European Mire VDB,Russian Federation,Polar and subpolar zone,1929-07-27,69.783333,31.900000,10.0,25.0,Not specified,NaN,NaN,NaN,False,?,Semi-natural,False,True,False,True,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.813,1.908,False,True,False,False

In [77]:
# Do another data check on the number of plots
df8 = (df7.groupby(['Species', 'Continent'], dropna=False)
           .agg({'PlotObservationID':'count'})
           .reset_index()
           .rename(columns={'PlotObservationID':'Count_plots_check'})
          )
df9 = pd.merge(df8, dfd, on=['Species', 'Continent'])
df9[df9['Count_plots_check'] != df9['Count_plots']]

,Species,Continent,Count_plots_check,Count_plots,GDE_Class,GDE_Cert,References,ExpertName,ExpertEmail,Notes
184,Aegilops neglecta,Asia,38,77,1.0,3.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,Europe
1796,Robinia pseudoacacia,Asia,17,4,1.0,1.0,NaN,Kristina Toderich,ktoderich@tottori-u.ac.jp,"Asia/Caucasus, Crimea and Central Asia"

In [78]:
# Export table
df7.to_csv(tbl_out, encoding='utf-8', index=False)
dfd.to_csv(tbl_out2, encoding='utf-8', index=False)